SYS-3135 - open sourcing summary pallet (#116)
Aventus-Network-Services/avn-parachain pull request #119
Opened 2023-02-03 13:51 UTC by ivan-cholakov

This PR does not change any functionality in the pallets.

2023-02-06 10:33 UTC, thadouk requested changes

2023-02-06 10:33 UTC, thadouk commented on pallets/summary/Cargo.toml
> +pallet-avn = { git = "https://github.com/Aventus-Network-Services/avn-parachain", tag = "v1.0.2", default-features = false }
I think these to be relative paths rather than fixed version values

2023-02-06 10:48 UTC, thadouk approved these changes

2023-02-07 15:15 UTC, fluorostani approved these changes

2023-02-07 15:19 UTC, alexpArtos approved these changes

2023-02-07 15:19 UTC, alexpArtos commented on pallets/summary/src/vote.rs
> + * **************************** */
```suggestion
/***************** Functions that run in an offchain worker context  **************** */
```

2023-02-07 15:19 UTC, alexpArtos commented on pallets/summary/src/vote.rs
> +    // time the vote gets mined It may be outside the voting window and get rejected.
```suggestion
    // time the vote gets mined. It may be outside the voting window and get rejected.
```

2023-02-07 15:28 UTC, merged