Sys 3695 remove ethereum transactions
Aventus-Network-Services/avn-parachain pull request #316
Opened 2023-11-27 16:02 UTC by ivan-cholakov

remove `ethereum-transactions` pallet and extended migration to drop the storage items from the pallet

2023-11-28 10:34 UTC, fluorostani commented on pallets/parachain-staking/src/benchmarks.rs
> +// };
Is this intentional?

2023-11-28 10:36 UTC, fluorostani approved these changes

2023-11-29 00:57 UTC, nahuseyoum requested changes

2023-11-29 00:57 UTC, nahuseyoum commented on runtime/avn/src/lib.rs
> +impl frame_support::traits::OnRuntimeUpgrade for SeedBridgeTransactionAndDropEthTransactions {
Can we please bring back the pre and post upgrade tests

2023-11-29 15:32 UTC, nahuseyoum approved these changes

2023-11-29 15:32 UTC, merged